[package]
name = "ruspiro-singleton"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.2.0" # remember to update html_root_url
description = "Simple and easy to use singleton pattern"
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-singleton/tree/v0.2.0"
documentation = "https://docs.rs/ruspiro-singleton/0.2.0"
readme = "README.md"
keywords = ["RusPiRo", "singleton", "raspberrypi"]
categories = ["no-std", "embedded"]
edition = "2018"

[lib]

[dependencies]
ruspiro-lock = "0.2"
ruspiro-interrupt-core = "0.2"

[features]

