[package]
name = "ruspiro-singleton"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.2.2" # remember to update html_root_url
description = "Simple and easy to use singleton pattern"
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-singleton"
documentation = "https://docs.rs/ruspiro-singleton/0.2.2"
readme = "README.md"
keywords = ["RusPiRo", "singleton", "raspberrypi"]
categories = ["no-std", "embedded"]
edition = "2018"

[badges]
travis-ci = { repository = "RusPiRo/ruspiro-singleton", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]

[dependencies]
ruspiro-lock = "0.2"

[features]

