[package]
name = "ruspiro-singleton"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.1" # remember to update html_root_url
description = ""
license = "LICENSE"
repository = ""
readme = "README.md"
keywords = ["ruspiro"]
categories = ["no_std"]
edition = "2018"

[lib]

[dependencies]
ruspiro-lock = { path = "../ruspiro-lock" }

[features]
